title: Settings
data:
  site_name: "Kaung Sat Hein (Destiny)"
  personality: casual
  show_signup: true
  social:
    - name: Twitter
      url: "https://twitter.com"
      icon: site/social-icons/twitter.svg
    - name: Github
      url: "https://github.com/KSHDestiny"
      icon: site/social-icons/github.svg
    - name: Email
      url: "mailto:kaungsathein.5899@gmail.com"
      icon: site/social-icons/email.svg
